[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "aois-lab2"
version = "0.1.0"
description = "Лабораторная работа 2 по АОИС"
requires-python = ">=3.11"
dependencies = []

[project.optional-dependencies]
dev = ["pytest>=8.0.0", "pytest-cov>=5.0.0"]

[project.scripts]
aois-lab2 = "boolfunc.cli:main"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
addopts = "--cov=boolfunc --cov-report=term-missing --cov-fail-under=90"
testpaths = ["tests"]
